# Generated by Django 4.2.3 on 2023-08-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp2FA', '0002_rename_profileimage_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='selfieimages/'),
        ),
    ]
