# Generated by Django 4.2.3 on 2023-08-04 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp2FA', '0004_rename_image_userimage_userimage_intuderimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntuderImage',
            new_name='IntruderImage',
        ),
    ]
