# Generated by Django 4.2.3 on 2023-08-04 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp2FA', '0005_rename_intuderimage_intruderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteList',
            fields=[
                ('websiteListID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
