# Generated by Django 4.2.3 on 2023-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp2FA', '0006_websitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelist',
            name='websiteName',
            field=models.CharField(default='Website', max_length=100),
        ),
    ]
