# Generated by Django 4.2.3 on 2023-08-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp2FA', '0007_websitelist_websitename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitelist',
            old_name='url',
            new_name='websiteUrl',
        ),
    ]
