# Generated by Django 4.2.3 on 2023-08-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp2FA', '0009_delete_intruderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntruderImage',
            fields=[
                ('IntruderImageID', models.AutoField(primary_key=True, serialize=False)),
                ('intruderImage', models.ImageField(blank=True, null=True, upload_to='intruderimages/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
