# Generated by Django 4.2.3 on 2023-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp2FA', '0010_intruderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelist',
            name='username',
            field=models.CharField(default='Website', max_length=100),
        ),
    ]
