# Generated by Django 4.2.3 on 2023-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp2FA', '0011_websitelist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelist',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
