# Generated by Django 4.2.3 on 2023-08-15 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webApp2FA', '0012_alter_websitelist_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntruderImage',
            new_name='FailedAuthen',
        ),
        migrations.RenameField(
            model_name='failedauthen',
            old_name='IntruderImageID',
            new_name='FailedAuthenID',
        ),
        migrations.RenameField(
            model_name='failedauthen',
            old_name='intruderImage',
            new_name='FailedAuthenImage',
        ),
    ]
