# Generated by Django 4.2.3 on 2023-08-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp2FA', '0013_rename_intruderimage_failedauthen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedauthen',
            name='FailedAuthenImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
